---
- name: Créer un conteneur LXC sur Proxmox
  hosts: localhost
  tasks:
    - name: Créer le conteneur
      proxmox_kvm:
        node: "nom_du_noeud_proxmox"
        api_user: "utilisateur_api"
        api_password: "mot_de_passe_api"
        api_host: "localhost"
        vmid: 100  
        ostemplate: "local:vztmpl/debian-10-standard_10.3-1_amd64.tar.gz"  
        hostname: "nom_du_conteneur"
        memory: 512  
        netif: "net0"  
        password: "mot_de_passe_conteneur"
        state: present

- name: Créer un conteneur LXC sur Proxmox
      
