---
- name: Rebuild NixOS configuration on all machines
  hosts: nixos
  vars:
    nixos_config_dir: /home/nixos/nixos-config
    nixos_repo: "https://github.com/Waddenn/nixos-config.git"
  tasks:
    - name: Update NixOS configuration from Git repository (without sudo)
      git:
        repo: "{{ nixos_repo }}"
        dest: "{{ nixos_config_dir }}"
        update: yes
        force: yes
      become: false  

    - name: Rebuild NixOS using flake (hostname={{ inventory_hostname }})
      command: "nixos-rebuild switch --flake .#{{ inventory_hostname }}"
      args:
        chdir: "{{ nixos_config_dir }}"
      become: true  
        